insert into peca(id_peca,descricao) values (1, 'ABS');
insert into peca(id_peca,descricao) values (2, 'Acelerador Elétrico');
insert into peca(id_peca,descricao) values (3, 'AirBag Banco');
--insert into peca(id_peca,descricao) values (4, 'AirBag Banco');
insert into peca(id_peca,descricao) values (5, 'AirBag Centralina');
insert into peca(id_peca,descricao) values (6, 'AirBag Conjunto');
insert into peca(id_peca,descricao) values (7, 'AirBag Cortina');
insert into peca(id_peca,descricao) values (8, 'AirBag Fita');
insert into peca(id_peca,descricao) values (9, 'AirBag Joelhos');
insert into peca(id_peca,descricao) values (10, 'AirBag Porta');
insert into peca(id_peca,descricao) values (11, 'AirBag Tablier');
insert into peca(id_peca,descricao) values (12, 'AirBag Volante');
insert into peca(id_peca,descricao) values (13, 'Alternador');
insert into peca(id_peca,descricao) values (14, 'Amortecedor Capot');
insert into peca(id_peca,descricao) values (15, 'Amortecedor FD');
insert into peca(id_peca,descricao) values (16, 'Amortecedor FE');
insert into peca(id_peca,descricao) values (17, 'Amortecedor mala ');
insert into peca(id_peca,descricao) values (18, 'Amortecedor TD');
insert into peca(id_peca,descricao) values (19, 'Amortecedor TE');
insert into peca(id_peca,descricao) values (20, 'Banco');
insert into peca(id_peca,descricao) values (21, 'Bloco motor');
insert into peca(id_peca,descricao) values (22, 'Bobine / Distribuidor');
insert into peca(id_peca,descricao) values (23, 'Bocal de depósito');
insert into peca(id_peca,descricao) values (24, 'Bomba DA');
insert into peca(id_peca,descricao) values (25, 'Bomba de alta pressão ');
insert into peca(id_peca,descricao) values (26, 'Bomba de gasolina/boia');
insert into peca(id_peca,descricao) values (27, 'Bomba de vácuo');
insert into peca(id_peca,descricao) values (28, 'Bomba repartidora');
insert into peca(id_peca,descricao) values (29, 'Bomba travão FD');
insert into peca(id_peca,descricao) values (30, 'Bomba travão FE');
insert into peca(id_peca,descricao) values (31, 'Bomba travão TD');
insert into peca(id_peca,descricao) values (32, 'Bomba travão TE');
insert into peca(id_peca,descricao) values (33, 'Braço de escova');
insert into peca(id_peca,descricao) values (34, 'Braço suspensão D');
insert into peca(id_peca,descricao) values (35, 'Braço suspensão E');
insert into peca(id_peca,descricao) values (36, 'BSI');
insert into peca(id_peca,descricao) values (37, 'BSM');
insert into peca(id_peca,descricao) values (38, 'Buzina');
insert into peca(id_peca,descricao) values (39, 'Cabeça motor');
insert into peca(id_peca,descricao) values (40, 'Caixa');
insert into peca(id_peca,descricao) values (41, 'Caixa direção');
insert into peca(id_peca,descricao) values (42, 'Caixa filtro ar');
insert into peca(id_peca,descricao) values (43, 'Canhão ignição');
insert into peca(id_peca,descricao) values (44, 'Capot');
insert into peca(id_peca,descricao) values (45, 'Catalizador');
insert into peca(id_peca,descricao) values (46, 'Cava da roda');
insert into peca(id_peca,descricao) values (47, 'Centralina');
insert into peca(id_peca,descricao) values (48, 'Chapeleira');
insert into peca(id_peca,descricao) values (49, 'Charrion');
insert into peca(id_peca,descricao) values (50, 'Cinto Central');
insert into peca(id_peca,descricao) values (51, 'Cinto D');
insert into peca(id_peca,descricao) values (52, 'Cinto E');
insert into peca(id_peca,descricao) values (53, 'Cinto FD');
insert into peca(id_peca,descricao) values (54, 'Cinto FE');
insert into peca(id_peca,descricao) values (55, 'Cinto TD');
insert into peca(id_peca,descricao) values (56, 'Cinto TE');
insert into peca(id_peca,descricao) values (57, 'Coletor de admisão');
insert into peca(id_peca,descricao) values (58, 'Coletor escape');
insert into peca(id_peca,descricao) values (59, 'Coluna direção');
insert into peca(id_peca,descricao) values (60, 'Comando de sofagem');
insert into peca(id_peca,descricao) values (61, 'Compressor AC');
insert into peca(id_peca,descricao) values (62, 'Comutador limpa vidros');
insert into peca(id_peca,descricao) values (63, 'Comutador luzes');
insert into peca(id_peca,descricao) values (64, 'Conjunto canhões');
insert into peca(id_peca,descricao) values (65, 'Conta KM');
insert into peca(id_peca,descricao) values (66, 'Depósito água radiador');
insert into peca(id_peca,descricao) values (67, 'Depósito combustível');
insert into peca(id_peca,descricao) values (68, 'Depósito DA');
insert into peca(id_peca,descricao) values (69, 'Depósito mija');
insert into peca(id_peca,descricao) values (70, 'Diferencial Frente');
insert into peca(id_peca,descricao) values (71, 'Diferencial Trás ');
insert into peca(id_peca,descricao) values (72, 'Display');
insert into peca(id_peca,descricao) values (73, 'Eixo Trás');
insert into peca(id_peca,descricao) values (74, 'Elevador D');
insert into peca(id_peca,descricao) values (75, 'Elevador E');
insert into peca(id_peca,descricao) values (76, 'Elevador FD');
insert into peca(id_peca,descricao) values (77, 'Elevador FE');
insert into peca(id_peca,descricao) values (78, 'Elevador roda suplente');
insert into peca(id_peca,descricao) values (79, 'Elevador TD');
insert into peca(id_peca,descricao) values (80, 'Elevador TE');
insert into peca(id_peca,descricao) values (81, 'Embaladeira D');
insert into peca(id_peca,descricao) values (82, 'Embaladeira E');
insert into peca(id_peca,descricao) values (83, 'Escape');
insert into peca(id_peca,descricao) values (84, 'Espelho D');
insert into peca(id_peca,descricao) values (85, 'Espelho E');
insert into peca(id_peca,descricao) values (86, 'Espelho interior ');
insert into peca(id_peca,descricao) values (87, 'Faról negoeiro D');
insert into peca(id_peca,descricao) values (88, 'Faról negoeiro E');
insert into peca(id_peca,descricao) values (89, 'Farolim TD');
insert into peca(id_peca,descricao) values (90, 'Farolim TE');
insert into peca(id_peca,descricao) values (91, 'Fecho D');
insert into peca(id_peca,descricao) values (92, 'Fecho E');
insert into peca(id_peca,descricao) values (93, 'Fecho FD');
insert into peca(id_peca,descricao) values (94, 'Fecho FE');
insert into peca(id_peca,descricao) values (95, 'Fecho mala');
insert into peca(id_peca,descricao) values (96, 'Fecho TD');
insert into peca(id_peca,descricao) values (97, 'Fecho TE');
insert into peca(id_peca,descricao) values (98, 'Forra porta');
insert into peca(id_peca,descricao) values (99, 'Frente (fibra ou chapa)');
insert into peca(id_peca,descricao) values (100, 'Grelha');
insert into peca(id_peca,descricao) values (101, 'Guarda lamas FD');
insert into peca(id_peca,descricao) values (102, 'Guarda lamas FE');
insert into peca(id_peca,descricao) values (103, 'Ilharga TD');
insert into peca(id_peca,descricao) values (104, 'Ilharga TE');
insert into peca(id_peca,descricao) values (105, 'Injetores');
insert into peca(id_peca,descricao) values (106, 'Interruptor luzes');
insert into peca(id_peca,descricao) values (107, 'Interruptor vidros');
insert into peca(id_peca,descricao) values (108, 'Interruptor vidros duplo');
insert into peca(id_peca,descricao) values (109, 'Jante');
insert into peca(id_peca,descricao) values (110, 'Limitador');
insert into peca(id_peca,descricao) values (111, 'Longarina D');
insert into peca(id_peca,descricao) values (112, 'Longarina E');
insert into peca(id_peca,descricao) values (113, 'Manga eixo D');
insert into peca(id_peca,descricao) values (114, 'Manga eixo E');
insert into peca(id_peca,descricao) values (115, 'Medidor massa ar');
insert into peca(id_peca,descricao) values (116, 'Módulos/Sensores');
insert into peca(id_peca,descricao) values (117, 'Molas');
insert into peca(id_peca,descricao) values (118, 'Motor ');
insert into peca(id_peca,descricao) values (119, 'Motor de arranque');
insert into peca(id_peca,descricao) values (120, 'Motor de sofagem');
insert into peca(id_peca,descricao) values (121, 'Motor limpa vidros frente');
insert into peca(id_peca,descricao) values (122, 'Motor limpa vidros trás');
insert into peca(id_peca,descricao) values (123, 'Motor mija');
insert into peca(id_peca,descricao) values (124, 'Motoventilador');
insert into peca(id_peca,descricao) values (125, 'Óculo traseiro');
insert into peca(id_peca,descricao) values (126, 'Ótica D');
insert into peca(id_peca,descricao) values (127, 'Ótica E');
insert into peca(id_peca,descricao) values (128, 'Pala sol');
insert into peca(id_peca,descricao) values (129, 'PC Frente');
insert into peca(id_peca,descricao) values (130, 'PC Trás');
insert into peca(id_peca,descricao) values (131, 'Pisca D');
insert into peca(id_peca,descricao) values (132, 'Pisca E');
insert into peca(id_peca,descricao) values (133, 'Pistolas de feicho');
insert into peca(id_peca,descricao) values (134, 'Plástico interior');
insert into peca(id_peca,descricao) values (135, 'Pneu');
insert into peca(id_peca,descricao) values (136, 'Polies');
insert into peca(id_peca,descricao) values (137, 'Porta D');
insert into peca(id_peca,descricao) values (138, 'Porta E');
insert into peca(id_peca,descricao) values (139, 'Porta FD');
insert into peca(id_peca,descricao) values (140, 'Porta FE');
insert into peca(id_peca,descricao) values (141, 'Porta lateral');
insert into peca(id_peca,descricao) values (142, 'Porta luvas');
insert into peca(id_peca,descricao) values (143, 'Porta TD');
insert into peca(id_peca,descricao) values (144, 'Porta TE');
insert into peca(id_peca,descricao) values (145, 'Puxadores (interior/exterior)');
insert into peca(id_peca,descricao) values (146, 'Radiador AC');
insert into peca(id_peca,descricao) values (147, 'Radiador de água');
insert into peca(id_peca,descricao) values (148, 'Radiador intercooler');
insert into peca(id_peca,descricao) values (149, 'Radiador sofagem ');
insert into peca(id_peca,descricao) values (150, 'Rádio');
insert into peca(id_peca,descricao) values (151, 'Reforço PC Frente');
insert into peca(id_peca,descricao) values (152, 'Reforço PC Trás');
insert into peca(id_peca,descricao) values (153, 'Régua de injeção');
insert into peca(id_peca,descricao) values (154, 'Roda ');
insert into peca(id_peca,descricao) values (155, 'Seletor velocidades');
insert into peca(id_peca,descricao) values (156, 'Servo freio');
insert into peca(id_peca,descricao) values (157, 'Sonda lambeda');
insert into peca(id_peca,descricao) values (158, 'Tampa combustível');
insert into peca(id_peca,descricao) values (159, 'Tampa da mala');
insert into peca(id_peca,descricao) values (160, 'Tejadilho');
insert into peca(id_peca,descricao) values (161, 'Terceiro Stop');
insert into peca(id_peca,descricao) values (162, 'Torre injeção / Carborador ');
insert into peca(id_peca,descricao) values (163, 'Transmissão D');
insert into peca(id_peca,descricao) values (164, 'Transmissão E');
insert into peca(id_peca,descricao) values (165, 'Traseira');
insert into peca(id_peca,descricao) values (166, 'Travão mão');
insert into peca(id_peca,descricao) values (167, 'Travessa inferior');
insert into peca(id_peca,descricao) values (168, 'Travessa superior');
insert into peca(id_peca,descricao) values (169, 'Triangulo D');
insert into peca(id_peca,descricao) values (170, 'Triangulo E');
insert into peca(id_peca,descricao) values (171, 'Tubo AC');
insert into peca(id_peca,descricao) values (172, 'Turbo');
insert into peca(id_peca,descricao) values (173, 'Válvulas');
insert into peca(id_peca,descricao) values (174, 'Veio de transmisão');
insert into peca(id_peca,descricao) values (175, 'Vidro D');
insert into peca(id_peca,descricao) values (176, 'Vidro E');
insert into peca(id_peca,descricao) values (177, 'Vidro FD');
insert into peca(id_peca,descricao) values (178, 'Vidro FE');
insert into peca(id_peca,descricao) values (179, 'Vidro Ilharga');
insert into peca(id_peca,descricao) values (180, 'Vidro TD');
insert into peca(id_peca,descricao) values (181, 'Vidro TE');
insert into peca(id_peca,descricao) values (182, 'Vidro Triangular');
insert into peca(id_peca,descricao) values (183, 'Viscoso');
insert into peca(id_peca,descricao) values (184, 'Volante');
insert into peca(id_peca,descricao) values (185, 'Volante motor / embraiagem ');
insert into peca(id_peca,descricao) values (186, 'Fundo mala');
insert into peca(id_peca,descricao) values (187, 'Bateria');
insert into peca(id_peca,descricao) values (188, 'Depósito abbleu');
insert into peca(id_peca,descricao) values (189, 'Caixa fusíveis ');
insert into peca(id_peca,descricao) values (190, 'Grelha Curcuvan');